### PR TITLE
Fix: Feature server REFER

### PR DESCRIPTION
**Pull request by two56**
I meant to get this pull request in earlier and #113 reminded me to do it. 

This is mostly correcting (I think) the old code. I'm returning a 488 if things go wrong.

I've tested the best I can, I getting audio!

### CODE REVIEW

**Comment by Megamuch** [comment]
I just tested this fix, and even though the REFER is now reported as successful, the audio is not switching. 
how did you test this? also with 2 FS, 1 SIP and 1 RTP ?

**Comment by Megamuch** [comment]
okay, my use case is a bit different which may have an influence here. 

Call flow is -> caller entry to queue and waits. 
outbound call is done through the web api
outbound call is answered and action hook is set to a Dequeue path. 
if the inbound and outbound call happen to be on different FS's, a refer will trigger to move the caller over to the callee. 
without your fix, this will throw an error on the sbc-inbound (see #113). 

With your fix this error is resolved, however, audio is not there. 
The caller remains in the queue (unable to be popped) and the callee will get dead air with a disconnect after 30 seconds(+/-).

**Comment by two56** [comment]
I believe it should be going through the same REFER procedure (dump context into redis, send invite with `context-` and pop off on the other feature server).

What version of rtpengine are you running? I may be clutching at straws, but I had issue with SIPREC (no audio I think) with mr11.3.1.8. I dropped back to mr11.2.1.5.

I've re-tested and I am getting two way audio. I'll do an mr11.3.1.8 RTP build and see what that gives me.

**Comment by two56** [comment]
I get two way audio with mr11.3.1.8. I'll try the enqueue, dequeue flow to check the patch in that scenario.

**Comment by two56** [comment]
I've tried an enqueue, REST dial, dequeue flow and I'm getting two way audio after the REFER.

**Comment by Megamuch** [comment]
Well that's odd. 
I'm running the 11.3.1.8 on ARM. (Since it was cheaper and never found an issue with it). 
I'll try to get a intel 11.3.1.8 build but also the version 11.2 as a test.

**Review by davehorton — APPROVED** [review]

**Pull request merged**
